# 配置模版
ticho:
  minio:
    endpoint: http://localhost
    accessKey: root
    secretKey: 123456
    imgSize: 10MB
    fileSize: 10MB
    defaultBucket: default
spring:
  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 1024MB
      # 上传数据总大小
      max-request-size: 1024MB
      enabled: true
      # 设置文件缓存的临界点,超过则先保存到临时目录,默认为0,所有文件都会进行缓存
      file-size-threshold: 0